feat: rename activity page into stats
betagouv/notification-admin pull request #9
Opened 2022-07-29 12:26 UTC by BenoitSerrano

2022-08-02 12:42 UTC, freesteph requested changes

2022-08-02 12:42 UTC, freesteph commented on app/templates/partials/nav/footer.html
> +          {% if 'footer:about' in i.description %}
indentation

2022-08-02 16:25 UTC, freesteph commented on app/templates/partials/page-content/counter.html
> +    class="wp-block-cover__inner-container py-doubleGutter flex flex-col space-y-doubleGutter lg:space-y-0 lg:flex-row lg:justify-between lg:items-baseline">
donc je pense que prettier a simplement mis à la ligne toutes les lignes jugées trop longues, dont celle-ci qui ne mérite pas sa coupure ; cela étant dit, tu peux enlever toutes les classes CSS sur cette `div` qui n'ont rien à voir avec le DSFR

2022-08-04 12:20 UTC, freesteph approved these changes
Looks good 🍸

2022-08-04 12:20 UTC, freesteph commented on app/templates/partials/page-content/counter.html
> +  <div>
double div?

2022-08-04 12:21 UTC, BenoitSerrano commented on app/templates/partials/page-content/counter.html
> +  <div>
L'autre se termine ailleurs, c'est un div qui comprend plusieurs div parallèles

2022-08-05 08:17 UTC, merged